### ISSUE TITLE
OSMC - please review your contribution

### ISSUE THREAD

**Issue by filip-jezek** [modelica/newsletter#34]
Hi Martin,

although the collaboration and friendship with OSMC, I had to reject most of the OSMC contributions from #16 . My general feeling is that you have mistaken this with OSMC newsletter, which is not. Vendors must have equal access to the MA channels. We can ask to have separate OSMC category, but I am afraid this wont pass through the board. 

Additionally, you advertise the articles which are over half a year old as news (since last newsletter - yes. Generally novel - not really). 

Please review my comments below:

- [ ] 1. OpenModelica 1.12.0 release
  - The leading paragraph is not new in any way. The target audience probably already heard about it. Please review for over-advertisement.
  - Please decide which version do you want to advertise - release or v1.13 beta?
- [ ] 2. OpenModelica 1.13.0 planned release
  - The leading paragraph is not new in any way. The target audience probably already heard about it. Please review for over-advertisement.
  - connected to the 1.12 release. IMO only one of these should be kept.
- [ ] 3. OpenModelica Arduino
  - This is a feature advertisement, not a new product. If you insist on having it, please shorten it and merge it into the new relase article.
- [ ] 4. OpenModelica OPC
  - A single feature is not worth separate article. Please shorten it, remove the pic and merge it into the article about chosen new version.
- [ ] 5. 3D animation
  - Again, this is an old feature description. Same as above - drop it or merge it.
- [x] 6. OMSimulator
  - Could you please reduce the number of pictures to one? The second one imho does not introduce anything new - you can (?) create a model, where you make use of both connectors at once.
- [ ] 7. OpenModelica / Modprod workshops
  - for both: PLease scale the images so they fit inline in a row. They could be links to full-sized image.
- [ ] 8. OMJulia / OMMatlab / OMPython
  - JULIA / matlab: Is it that the Julia interface is unique among the other tools? Then let it be separate article. Otherwise it is again a feature description with same consequences as above.
  - OMpython: Althgough same feature advertisement as above, I see this one more interesting. STill, do you consider to merge it into the article about the new release?

What about writing a full-length artcle about v1.12 release and new stuff in v1.13 and having it linked from the main newsletter page, with only a short descritption? I mean there is not a problem of having it hosted here, just the overall space in the newsletter *feed* page.

I need to close these issues by thursday / friday at most, so the newsletter could be sent on monday. Therefore, I require your input as soon as possible. 

Without your input, I would reject the feature descriptions and merge v.12 and v1.13 into one article and rescale the images in the workshops articles.

Thanks for your comments!

**Comment by sjoelund** [comment]
@petfr @arun3688 @bernhard-thiele: Any additional comments?

1. I don't agree that the target audience knows what OpenModelica is. The guidelines also do not say anything about advertisements; 

2. Yes only one of these should have been kept if there had been more newsletters. As it is, yes 1.12.0 is rather old, but at least we didn't push in 3 more releases that are new to the newsletter.

3-5. New features have been part of the newsletter in the past as far as I know. Otherwise they should be merged into the 1.12.0 description

6. @lochel: Could you fix this?

7. The images would fit nicely in a row on my screen; they are already small at the source (relative to screen size) at least when using raw kramdown to generate HTML (don't know what CSS you apply). Plenty of room to fit both images in one row if you'd like to move them.
![kramdown-image-size](https://user-images.githubusercontent.com/3016460/38012866-532b2ffa-3263-11e8-9b91-f5c869819ea5.png). If you need to have images scaled in such a way that they fit in the width of your drawing area, the guidelines needs a width to target in points (not pixels) so that we can scale it for any screen (I assume your screen is quite small if the images seem large); otherwise I would have assumed javascript scaled the images to fit a dynamic width.

8. The Julia / Matlab interfaces are new developments and if they would be moved should fit in the 1.13.0 text; OMPython is a lot older although with some new features for 1.12.0

I don't have time to work on this until next Thursday, although some of the co-authors could possibly have a look.

**Comment by petfr** [comment]
Dear Filip and All,

I agree with Martins comments below.


  1.  The introductory sentence about OpenModelica tells what it is for a person who is not an expert. Without this, it would be hard to know. Some people mistake OpenModelica with the Modelica language. Also the target

audience may not always be experts, and the newsletter will be on the web. This short explanatory text has appeared many times in previous newsletters edited by Mike Tiller. I see no reason to change the rules for this newsletter. Of course, one option would be to shorten it slightly, but then what/how?



  1.  Regarding 1.12.0 (October) and 1.13.0 (the coming one). The reason we have both is that there was no newsletter last year.  Of course, we could merge them, or only keep 1.12.0 and wait with 1.13.0 for the next newsletter (when is that, Sept 2018?)

As far as I know, OMJulia is a new feature among Modelica tools.

 It would be good to have a 5 min phone call today with you, Filip, to decide what to do.
My phone: + 46 13 281484

Best,

Peter

**Comment by filip-jezek** [comment]
Hi all, thanks for your reactions!

It is my first newsletter, so I am sorry for the complications. I have prepared the submission guidelines in more technical way and I assumed those https://modelica.org/publications/newsletters/guidelines still valid (*"(technical details only, no marketing or advertising content)"*). My fault, sorry again. I would merge also the content guidelines until next call for contributions.

Anyways, to the points:

1&2. Agreed. Although the statement seems a bit advertising ("the most complete"), it is true information.
Still, please decide, merge the 1.12 and 1.13 into one article. Next newsletter is in july, so that would be the right place to advertise v1.13

3-5: I went through the old newsletters. Truth, that the features are sometimes separate article, but only in case there is something unique - e.g. https://modelica.org/publications/newsletters/2014-3/index_html#item301 Therefore, is it possible to merge 3-5 into the new OM release info?

6: Solved

7: Again, my fault with the submission guidelines. The content column width is 620 px. Due to readability it does not scale with the screen size. Can I rescale them for you then?

8: Lets have OMJulia separate and integrate the OMPython?

The newsletter is due tuesday, but I could do the manual work, if you agree. Also, the pages could have some changes even after the nesletter is sent, as long as headings are the same.
F/

**Comment by sjoelund** [comment]
For 7, yes you can scale the figures, preferably using a 50% width on the image reference if they then both fit. Although I am a bit skeptical that the page renders fine with a fixed width. For example, this is how https://newsletter.modelica.org/2018-01/index is rendered on my laptop (and why having a fixed width in pixels is a bad idea):
![newsletter-current](https://user-images.githubusercontent.com/3016460/38026668-47226ee2-328d-11e8-9deb-369eef2444e6.png)

**Comment by xogeny** [comment]
Although I am no longer to editor so I'm not sure how much my opinion should count for here, I just want to say that language like "the most complete" would have also drawn my scrutiny as well.  My goal, as editor, was not to avoid advertising, but to make it not *read* like an advertising and the way I enforced that was to require articles to adhere closely to objective and factual information and avoid hyperbole and superlatives.  If there is an objective factual basis for making such a claim, then I would recommend you state the facts.  If not, I would replace "the most complete" with "an".

As far as the `v1.12` and `v1.13` articles are concerned, I recognize that it has been a long time between newsletters and so some items have been missed.  But I don't see the point in two different articles. Perhaps a compromise would be to change the article to inform people that `v1.13` has been released and then list big improvements since the last newsletter release announcement (*e.g.,* "since the release of 1.??, the following improvements have been introduced...").

As I said, this isn't my call.  Ultimately it is up to @filip-jezek (and ultimately the board).  I'm just trying to inject what I think a continuation of previous editorial policies would look like.

**Comment by petfr** [comment]
Dear Jezek,

Thanks for answers. See points below.

**Comment by petfr** [comment]
Hi Filip,

We skip the OM 1.13.0 Beta in this newsletter and take it instead in the July newsletter.
We have merged the items into the OM 1.12.0 news item.  Hopefully you can adjust sizes of pictures in a pixel-independent way.
We did not include Interactive simulation with OPC, since this is an OM 1.13.0 feature. Will put it in the July newsletter.

OMJulia with OMMatlab is still a separate item.

Best,

Peter

**Comment by filip-jezek** [comment]
Hi all,
@xogeny the contrary - I think your opinion is highly valuable here, thanks for the comment! I would be glad, if you continue to comment to have some continuation. Moreover, I totally agree with your comments here.

@sjoelund wow, nice resolution :) Is the page rendering (and overall graphics) great? No, it definitely isnt. I am a simple programmer, not a designer, so the plan is to pimp the visuals for the next releases.

@petfr 
> We skip the OM 1.13.0 Beta in this newsletter and take it instead in the July newsletter.
> We have merged the items into the OM 1.12.0 news item.  Hopefully you can adjust sizes of pictures in a pixel-independent way.
> We did not include Interactive simulation with OPC, since this is an OM 1.13.0 feature. Will put it in the July newsletter.
> OMJulia with OMMatlab is still a separate item.

Great! The newsletter has been agreed to be three times a year, that is every 4 months. @MartinOtter promised in the letter from the board the next contribution deadline to be 20 july. I also agree that the vacation time is not perfect timing, so maybe we should discuss to postpone it a bit so we have newsletter issued on mid September, January and May. But this should be discussed and confirmed by the board.

> Yes, merging is possible, 3-5 into the OM 1.12.0 release info.  Will you do it, or should we try to make a draft merge?

As an apology for incomplete submission guidelines I would do it for you today / tomorow and let you review it before sending out. Is this acceptable?

Thanks for your input! 
F/

**Comment by xogeny** [comment]
Sorry, I haven't followed the issues with layout/resolution.  But if there are issues about layout and responsiveness, ping me and I'll examine things and I'll contribute whatever comments I can to help.

**Comment by filip-jezek** [comment]
@petfr  Please review the changes, I am closing the issue. I dont think a call is necessary anymore, but if you do, please let me know.
